import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Discuss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
          <Providers>
            <Header />
        <div className="container min-h-screen mx-auto px-4 max-w-6xl">
            {children}
        </div>
          </Providers>
            <Footer />
      </body>
    </html>
  );
}
